name: "Generate SBOM"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f setup/requirements.txt ]; then pip install -r setup/requirements.txt; fi

      - name: Install Syft
        run: |
          SYFT_VERSION="v0.101.0"
          curl -sSL "https://github.com/anchore/syft/releases/download/${SYFT_VERSION}/syft_${SYFT_VERSION#v}_linux_amd64.tar.gz" -o syft.tar.gz
          tar -xzf syft.tar.gz syft
          sudo mv syft /usr/local/bin/

      - name: Generate SBOM with Syft
        run: syft . -o spdx-json > sbom.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json